//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  Edited by Rodrigo Soldi
//

enum ___VARIABLE_sceneName___Scene {
  
    // MARK: Use cases
  
    enum View {
        enum DidLoad {
            struct Request {
            }
            struct ViewModel {
            }
        }
    }
    
    enum DidTap {
        
    }
    
}
