//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  Edited by Rodrigo Soldi
//

protocol ___VARIABLE_sceneName___ViewControllerDelegate: HTGenericInteractorProtocol {

}

class ___VARIABLE_sceneName___Interactor: ___VARIABLE_sceneName___InteractorDelegate {
    
    weak var viewController: ___VARIABLE_sceneName___ViewControllerDelegate?
    lazy var worker = ___VARIABLE_sceneName___Worker()
    
    init(_ viewController: ___VARIABLE_sceneName___ViewControllerDelegate) {
        self.viewController = viewController
    }
    
    func viewDidLoad(_ request: ___VARIABLE_sceneName___Scene.View.DidLoad.Request) {
        
    }
  
}
