//
//  HTListInteractor.swift
//  HeroTransitions
//
//  Created by Rafaela Lourenço de Paula on 19/10/2018.
//  Copyright (c) 2018 Rafaela Lourenço de Paula. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  Edited by Rodrigo Soldi
//

protocol HTListViewControllerDelegate: HTGenericInteractorProtocol {
    func displayInformations(_ viewModel: HTListScene.View.DidLoad.ViewModel)
}

class HTListInteractor: HTListInteractorDelegate {
    
    weak var viewController: HTListViewControllerDelegate?
    lazy var worker = HTListWorker()
    
    init(_ viewController: HTListViewControllerDelegate) {
        self.viewController = viewController
    }
    
    func viewDidLoad(_ request: HTListScene.View.DidLoad.Request) {
        let items = worker.generateData()
        let viewModel = HTListScene.View.DidLoad.ViewModel(items: items)
        self.viewController?.displayInformations(viewModel)
    }
  
}
