//
//  HTListRouter.swift
//  HeroTransitions
//
//  Created by Rafaela Lourenço de Paula on 19/10/2018.
//  Copyright (c) 2018 Rafaela Lourenço de Paula. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  Edited by Rodrigo Soldi
//

enum Ancor {
    case navBar
    case label
    case textView
    case presentTextView
}

protocol HTListRouterDelegate: HTGenericRouterDelegate {
    func toDetail(withAncor: Ancor)
}

class HTListRouter: HTListRouterDelegate {
    
    weak var viewController: HTListViewController?
  
    init(_ viewController: HTListViewController) {
        self.viewController = viewController
    }
    
    func toDetail(withAncor: Ancor) {
        let detailViewController = HTDetailViewController.instance(withAncor)
        detailViewController.hero.isEnabled = true
        detailViewController.navigationController?.hero.isEnabled = true
        viewController?.navigationController?.hero.isEnabled = true
        viewController?.navigationController?.pushViewController(detailViewController, animated: true)
    }
}
