//
//  HTDetailInteractor.swift
//  HeroTransitions
//
//  Created by Rafaela Lourenço de Paula on 22/10/2018.
//  Copyright (c) 2018 Rafaela Lourenço de Paula. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  Edited by Rodrigo Soldi
//

protocol HTDetailViewControllerDelegate: HTGenericInteractorProtocol {

}

class HTDetailInteractor: HTDetailInteractorDelegate {
    
    weak var viewController: HTDetailViewControllerDelegate?
    lazy var worker = HTDetailWorker()
    
    init(_ viewController: HTDetailViewControllerDelegate) {
        self.viewController = viewController
    }
    
    func viewDidLoad(_ request: HTDetailScene.View.DidLoad.Request) {
        
    }
  
}
