//
//  HTDetailViewController.swift
//  HeroTransitions
//
//  Created by Rafaela Lourenço de Paula on 22/10/2018.
//  Copyright (c) 2018 Rafaela Lourenço de Paula. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  Edited by Rodrigo Soldi
//

import UIKit
import Hero

protocol HTDetailInteractorDelegate: class {
    func viewDidLoad(_ request: HTDetailScene.View.DidLoad.Request)
}

class HTDetailViewController: HTGenericViewController, HTDetailViewControllerDelegate {
    
    lazy var interactor: HTDetailInteractorDelegate? = HTDetailInteractor(self)
    lazy var router: HTDetailRouterDelegate? = HTDetailRouter(self)
    
    // MARK: View lifecycle
    
    
    // MARK: Actions
    
    
    // Mark: Protocols
    
    
}

extension HTDetailViewController {
    
    public static var instance: HTDetailViewController {
        let storyboard = UIStoryboard(name: String(describing: HTDetailViewController.self), bundle: nil)
        guard let viewController = storyboard.instantiateInitialViewController() as? HTDetailViewController else {
            fatalError("ViewController must be exists to load scene.")
        }
        return viewController
    }
    
}
