# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HeroTransitions' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for HeroTransitions
  pod 'Hero'

  target 'HeroTransitionsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HeroTransitionsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
