//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  Edited by Rodrigo Soldi
//

protocol ___VARIABLE_sceneName___RouterDelegate: CMGenericRouterDelegate {
  
}

class ___VARIABLE_sceneName___Router: ___VARIABLE_sceneName___RouterDelegate {
    
    weak var viewController: ___VARIABLE_sceneName___ViewController?
  
    init(_ viewController: ___VARIABLE_sceneName___ViewController) {
        self.viewController = viewController
    }
    
}
